## Basic Imports

In [21]:
import sys
!{sys.executable} -m pip install numpy pandas matplotlib wordcloud nltk

# Importing necessary libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

from wordcloud import WordCloud

import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')
nltk.download('punkt')

Requirement already satisfied: numpy in c:\users\zain\anaconda3\envs\python-starter\lib\site-packages (2.4.1)
Requirement already satisfied: pandas in c:\users\zain\anaconda3\envs\python-starter\lib\site-packages (2.3.3)
Requirement already satisfied: matplotlib in c:\users\zain\anaconda3\envs\python-starter\lib\site-packages (3.10.8)
Requirement already satisfied: wordcloud in c:\users\zain\anaconda3\envs\python-starter\lib\site-packages (1.9.6)
Requirement already satisfied: nltk in c:\users\zain\anaconda3\envs\python-starter\lib\site-packages (3.9.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\zain\anaconda3\envs\python-starter\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\zain\anaconda3\envs\python-starter\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\zain\anaconda3\envs\python-starter\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\zain\anaconda3\envs\python-starter\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\zain\anaconda3\envs\python-starter\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\zain\anaconda3\envs\python-starter\lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\zain\anaconda3\envs\python-starter\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\zain\anaconda3\envs\python-starter\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\zain\anaconda3\envs\python-starter\lib\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\zain\anaconda3\envs\python-starter\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: click in c:\users\zain\anaconda3\envs\python-starter\lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\users\zain\anaconda3\envs\python-starter\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\zain\anaconda3\envs\python-starter\lib\site-packages (from nltk) (2026.2.28)
Requirement already satisfied: tqdm in c:\users\zain\anaconda3\envs\python-starter\lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: six>=1.5 in c:\users\zain\anaconda3\envs\python-starter\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in c:\users\zain\anaconda3\envs\python-starter\lib\site-packages (from click->nltk) (0.4.6)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Zain\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Zain\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [22]:
# Read the CSV file
df = pd.read_csv('spam.csv')

# Display the first few rows of the DataFrame
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [23]:
df.drop(columns = ['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], inplace = True)
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [24]:
# Rename the columns name
df.rename(columns = {'v1': 'target', 'v2': 'text'}, inplace = True)
df.head()

  target                                               text
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

## Data Preprocessing

In [25]:
import sys
!{sys.executable} -m pip install scikit-learn

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['target'] = encoder.fit_transform(df['target'])

df.head()

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\zain\anaconda3\envs\python-starter\lib\site-packages (from scikit-learn) (2.4.1)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp313-cp313-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: joblib>=1.3.0 in c:\users\zain\anaconda3\envs\python-starter\lib\site-packages (from scikit-learn) (1.5.3)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp313-cp313-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.0 MB 161.1 kB/s eta 0:00:47
   -- ------------------------------------- 0.5/8.0 MB 161.1 kB/s eta 0:00:47
   -- ------------------------------------- 0.5/8.0 MB 161.1 kB/s eta 0:00:47
   -- ------------------------------------- 0.5/8.0 MB 161.1 kB/s eta 0:00:47
   -- ------------------------------------- 0.5/8.0 MB 161.1 kB/s eta 0:00:47
   -- ------------------------------------- 0.5/8.0 MB 161.1 kB/s eta 0:00:47
   -- ------------------------------------- 0.5/8.0 MB 161.1 kB/s eta 0:00:47
   -- ------------------------------------- 0.5/8.0 MB 161.1 kB/s eta 0:00:47
   -- ------------------------------------- 0.5/8.0 MB 161.1 kB/s eta 0:00:47
   -- ------------------------------------- 0.5/8.0 MB 161.1 kB/s eta 0:00:47
   --- ------------------------------------ 0.8/8.0 MB 140.9 kB/s eta 0:00:52
   --- ------------------------------------ 0.8/8.0 MB 140.9 kB/s eta 0:00:52
   --- ------------------------------------ 0.8/8.0 MB 140.9 kB/s eta 0:00:52
   --- ------------------------------------ 0.8/8.0 MB 140.9 kB/s eta 0:00:52
   --- ------------------------------------ 0.8/8.0 MB 140.9 kB/s eta 0:00:52
   --- ------------------------------------ 0.8/8.0 MB 140.9 kB/s eta 0:00:52
   --- ------------------------------------ 0.8/8.0 MB 140.9 kB/s eta 0:00:52
   --- ------------------------------------ 0.8/8.0 MB 140.9 kB/s eta 0:00:52
   --- ------------------------------------ 0.8/8.0 MB 140.9 kB/s eta 0:00:52
   --- ------------------------------------ 0.8/8.0 MB 140.9 kB/s eta 0:00:52
   --- ------------------------------------ 0.8/8.0 MB 140.9 kB/s eta 0:00:52
   --- ------------------------------------ 0.8/8.0 MB 140.9 kB/s eta 0:00:52
   ----- ---------------------------------- 1.0/8.0 MB 126.2 kB/s eta 0:00:56
   ----- ---------------------------------- 1.0/8.0 MB 126.2 kB/s eta 0:00:56
   ----- ---------------------------------- 1.0/8.0 MB 126.2 kB/s eta 0:00:56
   ----- ---------------------------------- 1.0/8.0 MB 126.2 kB/s eta 0:00:56
   ----- ---------------------------------- 1.0/8.0 MB 126.2 kB/s eta 0:00:56
   ----- ---------------------------------- 1.0/8.0 MB 126.2 kB/s eta 0:00:56
   ----- ---------------------------------- 1.0/8.0 MB 126.2 kB/s eta 0:00:56
   ----- ---------------------------------- 1.0/8.0 MB 126.2 kB/s eta 0:00:56
   ----- ---------------------------------- 1.0/8.0 MB 126.2 kB/s eta 0:00:56
   ----- ---------------------------------- 1.0/8.0 MB 126.2 kB/s eta 0:00:56
   ----- ---------------------------------- 1.0/8.0 MB 126.2 kB/s eta 0:00:56
   ----- ---------------------------------- 1.0/8.0 MB 126.2 kB/s eta 0:00:56
   ----- ---------------------------------- 1.0/8.0 MB 126.2 kB/s eta 0:00:56
   ----- ---------------------------------- 1.0/8.0 MB 126.2 kB/s eta 0:00:56
   ------ --------------------------------- 1.3/8.0 MB 114.2 kB/s eta 0:00:59
   ------ --------------------------------- 1.3/8.0 MB 114.2 kB/s eta 0:00:59
   ------ --------------------------------- 1.3/8.0 MB 114.2 kB/s eta 0:00:59
   ------ --------------------------------- 1.3/8.0 MB 114.2 kB/s eta 0:00:59
   ------ --------------------------------- 1.3/8.0 MB 114.2 kB/s eta 0:00:59
   ------ --------------------------------- 1.3/8.0 MB 114.2 kB/s eta 0:00:59
   ------ --------------------------------- 1.3/8.0 MB 114.2 kB/s eta 0:00:59
   ------ --------------------------------- 1.3/8.0 MB 114.2 kB/s eta 0:00:59
   ------- -------------------------------- 1.6/8.0 MB 119.4 kB/s eta 0:00:54
   ------- -------------------------------- 1.6/8.0 MB 119.4 kB/s eta 0:00:54
   ------- -------------------------------- 1.6/8.0 MB 119.4 kB/s eta 0:00:54
   ------- -------------------------------- 1.6/8.0 MB 119.4 kB/s eta 0:00:54
   ------- -------------------------------- 1.6/8.0 MB 119.4 kB/s eta 0:00:54
   ------- -------------------------------- 1.6/8.0 MB 119.4 kB/s eta 0:00:54
   ------- -------------------------------- 1.6/8.0 MB 119.4 kB/s eta 0:00:54
   ------- -------------------------------- 1.6/8.0 MB 119.4 kB/s eta 0:00:54
   ------- -------------------------------- 1.6/8.0 MB 119.4 kB/s eta 0:00:54
   ------- -------------------------------- 1.6/8.0 MB 119.4 kB/s eta 0:00:54
   ------- -------------------------------- 1.6/8.0 MB 119.4 kB/s eta 0:00:54
   ------- -------------------------------- 1.6/8.0 MB 119.4 kB/s eta 0:00:54
   ------- -------------------------------- 1.6/8.0 MB 119.4 kB/s eta 0:00:54
   --------- ------------------------------ 1.8/8.0 MB 115.8 kB/s eta 0:00:54
   --------- ------------------------------ 1.8/8.0 MB 115.8 kB/s eta 0:00:54
   --------- ------------------------------ 1.8/8.0 MB 115.8 kB/s eta 0:00:54
   --------- ------------------------------ 1.8/8.0 MB 115.8 kB/s eta 0:00:54
   --------- ------------------------------ 1.8/8.0 MB 115.8 kB/s eta 0:00:54
   --------- ------------------------------ 1.8/8.0 MB 115.8 kB/s eta 0:00:54
   --------- ------------------------------ 1.8/8.0 MB 115.8 kB/s eta 0:00:54
   --------- ------------------------------ 1.8/8.0 MB 115.8 kB/s eta 0:00:54
   --------- ------------------------------ 1.8/8.0 MB 115.8 kB/s eta 0:00:54
   --------- ------------------------------ 1.8/8.0 MB 115.8 kB/s eta 0:00:54
   --------- ------------------------------ 1.8/8.0 MB 115.8 kB/s eta 0:00:54
   ---------- ----------------------------- 2.1/8.0 MB 115.1 kB/s eta 0:00:52
   ---------- ----------------------------- 2.1/8.0 MB 115.1 kB/s eta 0:00:52
   ---------- ----------------------------- 2.1/8.0 MB 115.1 kB/s eta 0:00:52
   ---------- ----------------------------- 2.1/8.0 MB 115.1 kB/s eta 0:00:52
   ---------- ----------------------------- 2.1/8.0 MB 115.1 kB/s eta 0:00:52
   ---------- ----------------------------- 2.1/8.0 MB 115.1 kB/s eta 0:00:52
   ---------- ----------------------------- 2.1/8.0 MB 115.1 kB/s eta 0:00:52
   ---------- ----------------------------- 2.1/8.0 MB 115.1 kB/s eta 0:00:52
   ---------- ----------------------------- 2.1/8.0 MB 115.1 kB/s eta 0:00:52
   ---------- ----------------------------- 2.1/8.0 MB 115.1 kB/s eta 0:00:52
   ----------- ---------------------------- 2.4/8.0 MB 116.1 kB/s eta 0:00:49
   ----------- ---------------------------- 2.4/8.0 MB 116.1 kB/s eta 0:00:49
   ----------- ---------------------------- 2.4/8.0 MB 116.1 kB/s eta 0:00:49
   ----------- ---------------------------- 2.4/8.0 MB 116.1 kB/s eta 0:00:49
   ----------- ---------------------------- 2.4/8.0 MB 116.1 kB/s eta 0:00:49
   ----------- ---------------------------- 2.4/8.0 MB 116.1 kB/s eta 0:00:49
   ----------- ---------------------------- 2.4/8.0 MB 116.1 kB/s eta 0:00:49
   ----------- ---------------------------- 2.4/8.0 MB 116.1 kB/s eta 0:00:49
   ----------- ---------------------------- 2.4/8.0 MB 116.1 kB/s eta 0:00:49
   ----------- ---------------------------- 2.4/8.0 MB 116.1 kB/s eta 0:00:49
   ------------- -------------------------- 2.6/8.0 MB 116.5 kB/s eta 0:00:47
   ------------- -------------------------- 2.6/8.0 MB 116.5 kB/s eta 0:00:47
   ------------- -------------------------- 2.6/8.0 MB 116.5 kB/s eta 0:00:47
   ------------- -------------------------- 2.6/8.0 MB 116.5 kB/s eta 0:00:47
   ------------- -------------------------- 2.6/8.0 MB 116.5 kB/s eta 0:00:47
   ------------- -------------------------- 2.6/8.0 MB 116.5 kB/s eta 0:00:47
   ------------- -------------------------- 2.6/8.0 MB 116.5 kB/s eta 0:00:47
   ------------- -------------------------- 2.6/8.0 MB 116.5 kB/s eta 0:00:47
   ------------- -------------------------- 2.6/8.0 MB 116.5 kB/s eta 0:00:47
   -------------- ------------------------- 2.9/8.0 MB 118.8 kB/s eta 0:00:43
   -------------- ------------------------- 2.9/8.0 MB 118.8 kB/s eta 0:00:43
   -------------- ------------------------- 2.9/8.0 MB 118.8 kB/s eta 0:00:43
   -------------- ------------------------- 2.9/8.0 MB 118.8 kB/s eta 0:00:43
   -------------- ------------------------- 2.9/8.0 MB 118.8 kB/s eta 0:00:43
   -------------- ------------------------- 2.9/8.0 MB 118.8 kB/s eta 0:00:43
   -------------- ------------------------- 2.9/8.0 MB 118.8 kB/s eta 0:00:43
   -------------- ------------------------- 2.9/8.0 MB 118.8 kB/s eta 0:00:43
   --------------- ------------------------ 3.1/8.0 MB 122.2 kB/s eta 0:00:40
   --------------- ------------------------ 3.1/8.0 MB 122.2 kB/s eta 0:00:40
   --------------- ------------------------ 3.1/8.0 MB 122.2 kB/s eta 0:00:40
   --------------- ------------------------ 3.1/8.0 MB 122.2 kB/s eta 0:00:40
   --------------- ------------------------ 3.1/8.0 MB 122.2 kB/s eta 0:00:40
   --------------- ------------------------ 3.1/8.0 MB 122.2 kB/s eta 0:00:40
   ----------------- ---------------------- 3.4/8.0 MB 126.6 kB/s eta 0:00:37
   ----------------- ---------------------- 3.4/8.0 MB 126.6 kB/s eta 0:00:37
   ----------------- ---------------------- 3.4/8.0 MB 126.6 kB/s eta 0:00:37
   ----------------- ---------------------- 3.4/8.0 MB 126.6 kB/s eta 0:00:37
   ----------------- ---------------------- 3.4/8.0 MB 126.6 kB/s eta 0:00:37
   ----------------- ---------------------- 3.4/8.0 MB 126.6 kB/s eta 0:00:37
   ----------------- ---------------------- 3.4/8.0 MB 126.6 kB/s eta 0:00:37
   ----------------- ---------------------- 3.4/8.0 MB 126.6 kB/s eta 0:00:37
   ----------------- ---------------------- 3.4/8.0 MB 126.6 kB/s eta 0:00:37
   ------------------ --------------------- 3.7/8.0 MB 127.4 kB/s eta 0:00:34
   ------------------ --------------------- 3.7/8.0 MB 127.4 kB/s eta 0:00:34
   ------------------ --------------------- 3.7/8.0 MB 127.4 kB/s eta 0:00:34
   ------------------ --------------------- 3.7/8.0 MB 127.4 kB/s eta 0:00:34
   ------------------ --------------------- 3.7/8.0 MB 127.4 kB/s eta 0:00:34
   ------------------ --------------------- 3.7/8.0 MB 127.4 kB/s eta 0:00:34
   ------------------ --------------------- 3.7/8.0 MB 127.4 kB/s eta 0:00:34
   ------------------ --------------------- 3.7/8.0 MB 127.4 kB/s eta 0:00:34
   ------------------ --------------------- 3.7/8.0 MB 127.4 kB/s eta 0:00:34
   ------------------- -------------------- 3.9/8.0 MB 127.7 kB/s eta 0:00:32
   ------------------- -------------------- 3.9/8.0 MB 127.7 kB/s eta 0:00:32
   ------------------- -------------------- 3.9/8.0 MB 127.7 kB/s eta 0:00:32
   ------------------- -------------------- 3.9/8.0 MB 127.7 kB/s eta 0:00:32
   ------------------- -------------------- 3.9/8.0 MB 127.7 kB/s eta 0:00:32
   ------------------- -------------------- 3.9/8.0 MB 127.7 kB/s eta 0:00:32
   ------------------- -------------------- 3.9/8.0 MB 127.7 kB/s eta 0:00:32
   ------------------- -------------------- 3.9/8.0 MB 127.7 kB/s eta 0:00:32
   ------------------- -------------------- 3.9/8.0 MB 127.7 kB/s eta 0:00:32
   ------------------- -------------------- 3.9/8.0 MB 127.7 kB/s eta 0:00:32
   ------------------- -------------------- 3.9/8.0 MB 127.7 kB/s eta 0:00:32
   ------------------- -------------------- 3.9/8.0 MB 127.7 kB/s eta 0:00:32
   -------------------- ------------------- 4.2/8.0 MB 123.5 kB/s eta 0:00:31
   -------------------- ------------------- 4.2/8.0 MB 123.5 kB/s eta 0:00:31
   -------------------- ------------------- 4.2/8.0 MB 123.5 kB/s eta 0:00:31
   -------------------- ------------------- 4.2/8.0 MB 123.5 kB/s eta 0:00:31
   -------------------- ------------------- 4.2/8.0 MB 123.5 kB/s eta 0:00:31
   -------------------- ------------------- 4.2/8.0 MB 123.5 kB/s eta 0:00:31
   -------------------- ------------------- 4.2/8.0 MB 123.5 kB/s eta 0:00:31
   -------------------- ------------------- 4.2/8.0 MB 123.5 kB/s eta 0:00:31
   -------------------- ------------------- 4.2/8.0 MB 123.5 kB/s eta 0:00:31
   ---------------------- ----------------- 4.5/8.0 MB 124.9 kB/s eta 0:00:29
   ---------------------- ----------------- 4.5/8.0 MB 124.9 kB/s eta 0:00:29
   ---------------------- ----------------- 4.5/8.0 MB 124.9 kB/s eta 0:00:29
   ---------------------- ----------------- 4.5/8.0 MB 124.9 kB/s eta 0:00:29
   ---------------------- ----------------- 4.5/8.0 MB 124.9 kB/s eta 0:00:29
   ---------------------- ----------------- 4.5/8.0 MB 124.9 kB/s eta 0:00:29
   ---------------------- ----------------- 4.5/8.0 MB 124.9 kB/s eta 0:00:29
   ----------------------- ---------------- 4.7/8.0 MB 129.5 kB/s eta 0:00:26
   ----------------------- ---------------- 4.7/8.0 MB 129.5 kB/s eta 0:00:26
   ----------------------- ---------------- 4.7/8.0 MB 129.5 kB/s eta 0:00:26
   ----------------------- ---------------- 4.7/8.0 MB 129.5 kB/s eta 0:00:26
   ----------------------- ---------------- 4.7/8.0 MB 129.5 kB/s eta 0:00:26
   ----------------------- ---------------- 4.7/8.0 MB 129.5 kB/s eta 0:00:26
   ----------------------- ---------------- 4.7/8.0 MB 129.5 kB/s eta 0:00:26
   ------------------------ --------------- 5.0/8.0 MB 135.7 kB/s eta 0:00:23
   ------------------------ --------------- 5.0/8.0 MB 135.7 kB/s eta 0:00:23
   ------------------------ --------------- 5.0/8.0 MB 135.7 kB/s eta 0:00:23
   ------------------------ --------------- 5.0/8.0 MB 135.7 kB/s eta 0:00:23
   ------------------------ --------------- 5.0/8.0 MB 135.7 kB/s eta 0:00:23
   ------------------------ --------------- 5.0/8.0 MB 135.7 kB/s eta 0:00:23
   ------------------------ --------------- 5.0/8.0 MB 135.7 kB/s eta 0:00:23
   ------------------------ --------------- 5.0/8.0 MB 135.7 kB/s eta 0:00:23
   ------------------------ --------------- 5.0/8.0 MB 135.7 kB/s eta 0:00:23
   ------------------------ --------------- 5.0/8.0 MB 135.7 kB/s eta 0:00:23
   ------------------------ --------------- 5.0/8.0 MB 135.7 kB/s eta 0:00:23
   ------------------------ --------------- 5.0/8.0 MB 135.7 kB/s eta 0:00:23
   ------------------------ --------------- 5.0/8.0 MB 135.7 kB/s eta 0:00:23
   ------------------------ --------------- 5.0/8.0 MB 135.7 kB/s eta 0:00:23
   ------------------------ --------------- 5.0/8.0 MB 135.7 kB/s eta 0:00:23
   ------------------------ --------------- 5.0/8.0 MB 135.7 kB/s eta 0:00:23
   ------------------------ --------------- 5.0/8.0 MB 135.7 kB/s eta 0:00:23
   ------------------------ --------------- 5.0/8.0 MB 135.7 kB/s eta 0:00:23
   -------------------------- ------------- 5.2/8.0 MB 126.4 kB/s eta 0:00:22
   -------------------------- ------------- 5.2/8.0 MB 126.4 kB/s eta 0:00:22
   -------------------------- ------------- 5.2/8.0 MB 126.4 kB/s eta 0:00:22
   -------------------------- ------------- 5.2/8.0 MB 126.4 kB/s eta 0:00:22
   -------------------------- ------------- 5.2/8.0 MB 126.4 kB/s eta 0:00:22
   -------------------------- ------------- 5.2/8.0 MB 126.4 kB/s eta 0:00:22
   -------------------------- ------------- 5.2/8.0 MB 126.4 kB/s eta 0:00:22
   -------------------------- ------------- 5.2/8.0 MB 126.4 kB/s eta 0:00:22
   -------------------------- ------------- 5.2/8.0 MB 126.4 kB/s eta 0:00:22
   -------------------------- ------------- 5.2/8.0 MB 126.4 kB/s eta 0:00:22
   -------------------------- ------------- 5.2/8.0 MB 126.4 kB/s eta 0:00:22
   -------------------------- ------------- 5.2/8.0 MB 126.4 kB/s eta 0:00:22
   --------------------------- ------------ 5.5/8.0 MB 127.1 kB/s eta 0:00:20
   --------------------------- ------------ 5.5/8.0 MB 127.1 kB/s eta 0:00:20
   --------------------------- ------------ 5.5/8.0 MB 127.1 kB/s eta 0:00:20
   --------------------------- ------------ 5.5/8.0 MB 127.1 kB/s eta 0:00:20
   --------------------------- ------------ 5.5/8.0 MB 127.1 kB/s eta 0:00:20
   --------------------------- ------------ 5.5/8.0 MB 127.1 kB/s eta 0:00:20
   --------------------------- ------------ 5.5/8.0 MB 127.1 kB/s eta 0:00:20
   --------------------------- ------------ 5.5/8.0 MB 127.1 kB/s eta 0:00:20
   ---------------------------- ----------- 5.8/8.0 MB 129.9 kB/s eta 0:00:18
   ---------------------------- ----------- 5.8/8.0 MB 129.9 kB/s eta 0:00:18
   ---------------------------- ----------- 5.8/8.0 MB 129.9 kB/s eta 0:00:18
   ---------------------------- ----------- 5.8/8.0 MB 129.9 kB/s eta 0:00:18
   ---------------------------- ----------- 5.8/8.0 MB 129.9 kB/s eta 0:00:18
   ---------------------------- ----------- 5.8/8.0 MB 129.9 kB/s eta 0:00:18
   ---------------------------- ----------- 5.8/8.0 MB 129.9 kB/s eta 0:00:18
   ------------------------------ --------- 6.0/8.0 MB 132.0 kB/s eta 0:00:15
   ------------------------------ --------- 6.0/8.0 MB 132.0 kB/s eta 0:00:15
   ------------------------------ --------- 6.0/8.0 MB 132.0 kB/s eta 0:00:15
   ------------------------------ --------- 6.0/8.0 MB 132.0 kB/s eta 0:00:15
   ------------------------------ --------- 6.0/8.0 MB 132.0 kB/s eta 0:00:15
   ------------------------------ --------- 6.0/8.0 MB 132.0 kB/s eta 0:00:15
   ------------------------------ --------- 6.0/8.0 MB 132.0 kB/s eta 0:00:15
   ------------------------------ --------- 6.0/8.0 MB 132.0 kB/s eta 0:00:15
   ------------------------------- -------- 6.3/8.0 MB 134.4 kB/s eta 0:00:13
   ------------------------------- -------- 6.3/8.0 MB 134.4 kB/s eta 0:00:13
   ------------------------------- -------- 6.3/8.0 MB 134.4 kB/s eta 0:00:13
   ------------------------------- -------- 6.3/8.0 MB 134.4 kB/s eta 0:00:13
   ------------------------------- -------- 6.3/8.0 MB 134.4 kB/s eta 0:00:13
   ------------------------------- -------- 6.3/8.0 MB 134.4 kB/s eta 0:00:13
   -------------------------------- ------- 6.6/8.0 MB 138.9 kB/s eta 0:00:11
   -------------------------------- ------- 6.6/8.0 MB 138.9 kB/s eta 0:00:11
   -------------------------------- ------- 6.6/8.0 MB 138.9 kB/s eta 0:00:11
   -------------------------------- ------- 6.6/8.0 MB 138.9 kB/s eta 0:00:11
   -------------------------------- ------- 6.6/8.0 MB 138.9 kB/s eta 0:00:11
   -------------------------------- ------- 6.6/8.0 MB 138.9 kB/s eta 0:00:11
   ---------------------------------- ----- 6.8/8.0 MB 141.8 kB/s eta 0:00:09
   ---------------------------------- ----- 6.8/8.0 MB 141.8 kB/s eta 0:00:09
   ---------------------------------- ----- 6.8/8.0 MB 141.8 kB/s eta 0:00:09
   ---------------------------------- ----- 6.8/8.0 MB 141.8 kB/s eta 0:00:09
   ---------------------------------- ----- 6.8/8.0 MB 141.8 kB/s eta 0:00:09
   ---------------------------------- ----- 6.8/8.0 MB 141.8 kB/s eta 0:00:09
   ---------------------------------- ----- 6.8/8.0 MB 141.8 kB/s eta 0:00:09
   ----------------------------------- ---- 7.1/8.0 MB 143.4 kB/s eta 0:00:07

   target                                               text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [26]:
#check duplicate values
df.duplicated().sum()

np.int64(403)

In [27]:
len(df)

5572

In [28]:
#remove Duplicate
df = df.drop_duplicates(keep = 'first')
len(df)

5169

## Feature Engg

In [29]:
# Importing the Porter Stemmer for text stemming
from nltk.stem.porter import PorterStemmer

# Importing the string module for handling special characters
import string

# Creating an instance of the Porter Stemmer
ps = PorterStemmer()

In [30]:
# Lowercase transformation and text preprocessing function
def transform_text(text):
    # Transform the text to lowercase
    text = text.lower()
    
    # Tokenization using NLTK
    text = nltk.word_tokenize(text)
    
    # Removing special characters
    y = []
    for i in text:
        if i.isalnum():
            y.append(i)
            
    # Removing stop words and punctuation
    text = y[:]
    y.clear()
    
    # Loop through the tokens and remove stopwords and punctuation
    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)
        
    # Stemming using Porter Stemmer
    text = y[:]
    y.clear()
    for i in text:
        y.append(ps.stem(i))
    
    # Join the processed tokens back into a single string
    return " ".join(y)

In [31]:
transform_text('Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...')

LookupError:
**********************************************************************
  Resource 'punkt_tab' not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')

  For more information see: https://www.nltk.org/data.html

  Attempted to load 'tokenizers/punkt_tab/english/'

  Searched in:
    - 'C:\\Users\\Zain/nltk_data'
    - 'c:\\Users\\Zain\\anaconda3\\envs\\python-starter\\nltk_data'
    - 'c:\\Users\\Zain\\anaconda3\\envs\\python-starter\\share\\nltk_data'
    - 'c:\\Users\\Zain\\anaconda3\\envs\\python-starter\\lib\\nltk_data'
    - 'C:\\Users\\Zain\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

In [ ]:
df['transformed_text'] = df['text'].apply(transform_text)
df.head()

,target,text,transformed_text
0,0,"Go until jurong point, crazy.. Available only ...",go jurong point crazi avail bugi n great world...
1,0,Ok lar... Joking wif u oni...,ok lar joke wif u oni
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,free entri 2 wkli comp win fa cup final tkt 21...
3,0,U dun say so early hor... U c already then say...,u dun say earli hor u c alreadi say
4,0,"Nah I don't think he goes to usf, he lives aro...",nah think goe usf live around though

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
tfid = TfidfVectorizer(max_features = 500)

In [ ]:
X = tfid.fit_transform(df['transformed_text']).toarray()
y = df['target'].values

## Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test , y_train, y_test = train_test_split(X,y,test_size = 0.20, random_state = 2)

## Model Training

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

In [ ]:
svc = SVC(kernel= "sigmoid", gamma  = 1.0)
knc = KNeighborsClassifier()
mnb = MultinomialNB()
dtc = DecisionTreeClassifier(max_depth = 5)
lrc = LogisticRegression(solver = 'liblinear', penalty = 'l1')
rfc = RandomForestClassifier(n_estimators = 50, random_state = 2 )
abc = AdaBoostClassifier(n_estimators = 50, random_state = 2)
bc = BaggingClassifier(n_estimators = 50, random_state = 2)
etc = ExtraTreesClassifier(n_estimators = 50, random_state = 2)
gbdt = GradientBoostingClassifier(n_estimators = 50, random_state = 2)    
xgb  = XGBClassifier(n_estimators = 50, random_state = 2)

In [ ]:
clfs = {
    'SVC': svc,
    'KNN': knc,
    'NB': mnb,
    'DT': dtc,
    'LR': lrc,
    'RF': rfc,
    'Adaboost': abc,
    'Bgc': bc,
    'ETC': etc,
    'GBDT': gbdt,
    'xgb': xgb
    
}

## Model Evaluation

In [ ]:
from sklearn.metrics import accuracy_score, precision_score
def train_classifier(clfs, X_train, y_train, X_test, y_test):
    clfs.fit(X_train,y_train)
    y_pred = clfs.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    return accuracy , precision

In [ ]:
accuracy_scores = []
precision_scores = []
for name , clfs in clfs.items():
    current_accuracy, current_precision = train_classifier(clfs, X_train, y_train, X_test, y_test)
    print()
    print("For: ", name)
    print("Accuracy: ", current_accuracy)
    print("Precision: ", current_precision)
    
    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)

For:  SVC
Accuracy:  0.9661508704061895
Precision:  0.9327731092436975

For:  KNN
Accuracy:  0.9274661508704062
Precision:  1.0

For:  NB
Accuracy:  0.9709864603481625
Precision:  0.9655172413793104

For:  DT
Accuracy:  0.9381044487427466
Precision:  0.9021739130434783

For:  LR
Accuracy:  0.9632495164410058
Precision:  0.9629629629629629

For:  RF
Accuracy:  0.971953578336557
Precision:  0.943089430894309

For:  Adaboost
Accuracy:  0.9613152804642167
Precision:  0.9375

For:  Bgc
Accuracy:  0.965183752417795
Precision:  0.9180327868852459

For:  ETC
Accuracy:  0.9729206963249516
Precision:  0.9296875

For:  GBDT
Accuracy:  0.9506769825918762
Precision:  0.9393939393939394

For:  xgb
Accuracy:  0.9709864603481625
Precision:  0.9576271186440678